[defaultConfig]
enabled = true
type = "LINEAR"
linearFogStartMult = 0.25
linearFogEndMult = 1.0
expFogMult = 3.0
exp2FogMult = 1.75
[dimensions."world_blender:world_blender"]
enabled = true
type = "LINEAR"
linearFogStartMult = 0.25
linearFogEndMult = 1.0
expFogMult = 3.0
exp2FogMult = 1.75
